version: 0.0
os: linux
files:
  - source: target/
    destination: /home/ec2-user/student3/
hooks:
  AfterInstall:
   - location: setup.sh
     runas: root
  ApplicationStart:
   - location: run.sh
     runas: root
